name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  QualityAssurance:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Lint
        run: npm run lint
      - name: Type check
        run: npm run type-check
      - name: Formatting check
        run: npx prettier